runtime: nodejs14
#env: flex
#automatic_scaling:
#  min_num_instances: 1
#  max_num_instances: 100
#  cool_down_period_sec: 180
#  cpu_utilization:
#    target_utilization: 0.6
#  target_concurrent_requests: 100
